apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: lab5
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: http
    path: /metrics
    interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  namespace: lab5
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: http
    path: /metrics
    interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: backend-alerts
  namespace: lab5
  labels:
    release: prometheus
spec:
  groups:
  - name: backend.rules
    rules:
    - alert: BackendDown
      expr: up{job="backend"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Backend сервис недоступен"
        description: "Pod {{ $labels.pod }} не отвечает более 1 минуты."
    - alert: HighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{namespace="lab5"}[5m]) > 0.08
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Высокая нагрузка CPU в namespace lab5"
