apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
  namespace: lab5
spec:
  parallelism: 5
  completions: 5
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: load-generator
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            wget -q -O- http://backend-service:5000/api/info > /dev/null 2>&1
            wget -q -O- http://backend-service:5000/health   > /dev/null 2>&1
          done
        resources:
          requests:
            cpu: "100m"
            memory: "32Mi"
          limits:
            cpu: "200m"
            memory: "64Mi"
